FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json .

RUN npm ci --omit=dev
COPY . .
RUN npm run build
FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN addgroup -S rakshith && adduser -S rakshith -G rakshith
USER rakshith
EXPOSE 80
CMD ["nginx","-g","daemon off;"]

