pipeline{
    agent any
    tools{
        nodejs 'node22'
    }
    environment{
        SCANNER_HOME=tool 'sonar-scanner'
        AWS_ACCOUNT_ID = credentials('ACCOUNT_ID_CHAT')
        AWS_ECR_REPO_NAME = credentials('ECR_REPO2_CHAT')
        AWS_DEFAULT_REGION = 'ap-south-1'
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
    }
    stages{
        stage("cleanws")
        {
            steps{
                cleanWs()
            }
        }
        stage("Checkout code"){
            steps{
          
                    git branch: "main",url: 'https://github.com/Rakshithrpoojary/chatapp-k8.git',credentialsId: 'git-cred'
                
            }
        }
        stage("Install pakages")
        {
            steps{
                dir('backend')
                {
                    sh "npm install"
                }
            }
        }
        stage("Trivy scanner for dependency")
        {
            steps{
                sh "trivy fs . > trivy.txt"
            }
        }
        stage("Sonar scann")
        {
            steps{
                dir("backend"){
                withSonarQubeEnv("sonar-cred-main")
                {
                 sh ''' $SCANNER_HOME/bin/sonar-scanner \
                 -Dsonar.projectName="ecommercesecondbackend" \
                 -Dsonar.projectKey="ecommercesecondbackend"
                 '''   
                }
                }
             
            }
        }
        stage("quality gate")
        {
            steps{
                waitForQualityGate(abortPipeline: false, credentialsId:'sonar-token')
            }
        }
        stage('build docker image'){
            steps{
                   sh  'docker system prune -f'
                   sh  'docker build -t ${AWS_ECR_REPO_NAME} backend'   
            }
        }
        stage("Scan docker image")
        {
            steps{
                sh 'trivy image ${AWS_ECR_REPO_NAME} > trivyimage.txt'
            }
        }
        stage("Push to ecr")
        {
            steps{
                sh 'aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}'
                sh 'docker tag ${AWS_ECR_REPO_NAME} ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}'
                sh 'docker push ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}'
            }
        }
    }


    

}
